---
# apache_repository: ppa:ptn107/apache
apache_repository: ppa:jonathan00/apache2

apache_install:
  - apache2

apache_module_disable: false
apache_module_enable:
  - rewrite
  - alias
  - auth_basic
  - authn_file
  - authz_groupfile
  - authz_host
  - authz_user
  - autoindex
  - cgi
  - deflate
  - dir
  - env
  - mime
  - negotiation
  - reqtimeout
  - rewrite
  - setenvif
  - status

apache_site_disable:
  - 000-default
  - default-ssl

apache_vhosts:
  - index: index.php
    directory_extra:
      - RewriteEngine On
