---
- name: Add repository to install the correct Apache version
  apt_repository: repo=ppa:jonathan00/apache2 update_cache=yes
  when: apacheversion == '2.2'

- name: Install Apache
  sudo: yes
  apt: pkg=apache2 state=present

- name: Install Apache Modules
  apache2_module: state=present name={{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

- shell: apache2 -v
  register: apache_version

- name: Change default apache2.4 site
  sudo: yes
  template: src=vhost24.conf.tpl dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.4.') != -1

- name: Change default apache2.2 site
  sudo: yes
  template: src=vhost22.conf.tpl dest=/etc/apache2/sites-available/default
  notify: restart apache
  when: apache_version.stdout.find('Apache/2.2.') != -1

- name: Install php apache module
  apt: name=libapache2-mod-php5 state=present
  when: parameters['php'] is defined
  notify: restart apache
