---

- name: Add apache vhosts configurations
  template:
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/{{ servername }}.conf
    owner=root group=root mode=644
  notify: Restart apache
  with_items: apache_vhosts
  when: apache_vhosts != false
