---
- name: add brightbox ppa
  apt_repository: repo='ppa:brightbox/ruby-ng-experimental' state=present update_cache=yes

- name: install ruby
  apt: pkg="{{ item }}" state=installed
  with_items:
    - "ruby{{ ruby_version }}"
    - rubygems
    - ruby-switch

- name: set ruby as default
  shell: "ruby-switch --set ruby{{ ruby_version }}"
  register: ruby_switch
  changed_when: ruby_switch.stdout != ""

- name: install bundler
  gem: name="bundler" user_install="no" state="present"

- name: install the different Gems
  gem: name={{ item }} user_install=no state=present
  with_items: ruby_global_gems
