---
- name: Fix php5-5.4 repository name
  set_fact:
    php_ppa: php5-oldstable
  when: php_ppa == 'php5-5.4'
- name: Add PHP ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php_ppa }}
- name: Install PHP packages
  run_once: true
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-cli
    - php5-imagick
    - php5-curl
    - php5-gd
    - php5-fpm
    - php5-memcached
    - php5-mysql
    - php5-pgsql
    - php5-xdebug
    - phpunit
    - php-pear
    - php5-mcrypt
    - php5-intl
- name: Install PECL packages
  apt: pkg="php5-dev" state=present

- name: Install Package
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: pecl_packages

- name: Create extension .ini file
  template: >
    src="extension.tpl"
    dest="/etc/php5/mods-available/{{ item }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: pecl_packages
  notify: php5-fpm restart

- name: Enable extension
  shell: php5enmod {{ item }}
  with_items: pecl_packages
  notify: php5-fpm restart

- name: ensure timezone is set
  lineinfile: dest=/etc/php5/cli/php.ini regexp='date.timezone =' line='date.timezone = {{ timezone }}'
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='date.timezone =' line='date.timezone = {{ timezone }}'
  notify: php5-fpm restart

- name: Configure Xdebug
  lineinfile: dest=/etc/php5/mods-available/xdebug.ini regexp={{ item }} line={{ item }}
  with_items:
    - 'xdebug.coverage_enable=1'
    - 'xdebug.default_enable=1'
    - 'xdebug.remote_enable=true'
    - 'xdebug.remote_connect_back=true'
    - 'xdebug.remote_host={{ php_xdebug_remote_host }}'
    - 'xdebug.remote_port={{ php_xdebug_remote_port }}'
    - 'xdebug.remote_handler=dbgp'
    - 'xdebug.remote_log=/tmp/xdebug.log'
    - 'xdebug.remote_autostart=false'
    - 'xdebug.idekey={{ php_xdebug_idekey }}'
    - 'xdebug.max_nesting_level={{ php_xdebug_max_nesting_level }}'
  notify: php5-fpm restart
