---
- name: checking installed version of nodejs
  shell: /usr/bin/test "$({{ nodejs_path }}bin/node -v 2> /dev/null)" = {{ nodejs_version_tag }}
  register: wanted_version_installed
  ignore_errors: True
  changed_when: "wanted_version_installed.rc == 1"

- name: download
  get_url: url={{ nodejs_tarball_url }} dest={{ nodejs_tmp_dir}}{{nodejs_file_name }}
  when: wanted_version_installed.rc == 1

- name: "verify SHASUM
  shell: curl {{ nodejs_shasum_url }} | grep {{ nodejs_file_name }} | sha1sum -c chdir={{ nodejs_tmp_dir }}
  when: wanted_version_installed.rc == 1

- name: unpack
  command: tar -xvzf {{ nodejs_file_name }} chdir={{ nodejs_tmp_dir }}
  when: wanted_version_installed.rc == 1

- name: compile and install
  shell: ./configure --prefix={{ nodejs_path }} && make && make install chdir={{ nodejs_tmp_dir }}{{ nodejs_file_tag }}
  sudo: true
  when: wanted_version_installed.rc == 1

- name: npm install global packages
  npm: name={{ item }} global=yes
  with_items: nodejs_global_packages
