---
- name: Install Nginx GPG key
  run_once: true
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Enable Nginx stable repo
  run_once: true
  apt_repository: repo='deb http://nginx.org/packages/ubuntu {{ ansible_lsb.codename }} nginx' state=present update_cache=yes

- name: Install nginx
  run_once: true
  apt: name=nginx state=present
  notify:
    - nginx restart
    - update-rc nginx

- name: Ensure /etc/nginx directories exist
  run_once: true
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: create self-signed SSL cert
  run_once: true
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=CA" -days 3650 -keyout /etc/nginx/{{ host }}.key -out /etc/nginx/{{ host }}.crt -extensions v3_ca creates=/etc/nginx/{{ host }}.crt
  notify: nginx restart
- name: Configure /etc/nginx/nginx.conf
  run_once: true
  template: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: nginx restart
- name: Do /etc/nginx/sites-available/{{ host }}.conf
  run_once: true
  template: src=etc/nginx/sites-available/default.tpl dest=/etc/nginx/sites-available/{{ host }}.conf owner=root group=root mode=0644
  notify: nginx restart
- name: Symlink of {{ host }}.conf
  run_once: true
  file: src=/etc/nginx/sites-available/{{ host }}.conf dest=/etc/nginx/sites-enabled/{{ host }}.conf state=link
  notify: nginx restart
- name: Do nginx upstream.conf
  run_once: true
  template: src=etc/nginx/conf.d/upstream.conf dest=/etc/nginx/conf.d/upstream.conf owner=root group=root mode=0644
  notify: nginx restart

- name: Remove default.conf
  run_once: true
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: Remove default conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/default.conf state=absent
- name: Remove example ssl conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent

- name: Make sure Nginx is running
  run_once: true
  service: name=nginx state=started enabled=yes
