---
- hosts: all
  sudo: true
  vars_files:
    - ../parameters.yml
    - vars/mysql.yml
    - vars/php.yml
    - vars/server.yml
    - vars/ruby.yml
    - vars/nodejs.yml
  roles:
    - common
    - role: nginx
      when: parameters['nginx'] is defined
    - role: apache
      when: parameters['apache'] is defined
    - role: hhvm
      when: parameters['php']['switcher'] is defined and parameters['php']['switcher'] == 'hhvm'
    - role: php
      when: parameters['php'] is defined
    - role: mysql
      when: parameters['mysql'] is defined
    - role: memcached
      when: parameters['memcached'] is defined
    - role: ruby
      when: parameters['ruby'] is defined
    - role: nodejs
      when: parameters['nodejs'] is defined
  tasks:
    - name: Add bash configuration
      template: >
        src="roles/common/templates/bash.tpl"
        dest="/home/vagrant/.bash_aliases"
        owner="root"
        group="root"
        mode=0644
